### ISSUE TITLE
Missing opencleanVis.js in pip installation

### ISSUE THREAD

**Issue by SetoNaikai** [VIDA-NYU/openclean#6]
After installing openclean-notebook missing opencleanVis.js in pip installation.

FileNotFoundError: [Errno 2] No such file or directory: '/home/username/miniconda3/envs/ssl/lib/python3.8/site-packages/openclean_notebook/controller/../ui/build/opencleanVis.js'

**To Reproduce**
1. Run Parking Violations - Profiling and Cleaning Example.ipynb
2. Run At Line 31 # Show GUI spreadsheet view for a sample of 1000 rows from the dataset.
db.edit('street_cleaning_violations', n=1000, random_state=42)
3. FileNotFoundError: [Errno 2] No such file or directory: '/home/[username]/miniconda3/envs/ssl/lib/python3.8/site-packages/openclean_notebook/controller/../ui/build/opencleanVis.js'
4. Double checked that the file is truly missing when navigating to the expected area in home directory.

**Expected behavior**
See the built in GUI spreadsheet view based on the expected files being present to load in the code. 

**Desktop (please complete the following information):**
 - OS: PRETTY_NAME="Debian GNU/Linux 10 (buster)"

**Additional context**
- Python Version: Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

**Comment by heikomuller** [comment]
This should be fixed now by #7 (Release 0.2.1)
